// Image assets served from Lovable CDN
const A = (id: string, name: string) => `/__l5e/assets-v1/${id}/${name}`;

const IMG = {
  sunriseSafari: A("da5638c2-2390-4f35-9cee-197f6d4fd690", "sunrise-safari.webp"),
  oneDay: A("fe5cc5fe-2029-4a79-b278-db4d22745392", "one-day.jpg"),
  routeA: A("c2f9fff6-ef70-4b8a-b9a4-f02831608d1f", "route-a.jpg"),
  camping: A("470574f0-0a8b-40a3-8a72-401e6d46d29e", "camping.jpg"),
  realDesert: A("38357a3a-bcb8-4ab6-8fad-843c43ba3f2f", "real-desert.jpg"),
  liveEntertainment: A("021fff4e-fd91-4fc5-b95a-fcc2f47f8efb", "live-entertainment.jpg"),
  danceMusic: A("59b8ea8a-f4c9-4908-ab8a-8b363e0f7204", "dance-music.jpg"),
  cultural: A("519fc2cb-5880-44d0-b18e-47b01872af7f", "cultural.jpg"),
  nonTouristic: A("d572af01-f38d-4283-9e56-a61f065bdb72", "non-touristic.jpg"),
  thar4n5d: A("7ec29392-6159-4f76-889c-7f1d715d62f8", "thar-4n5d.jpg"),
  thar7n8d: A("13757850-9463-4f54-bae7-a7057ad6c60e", "thar-7n8d.jpg"),
  luxuryCamp: A("5e5d8f72-00eb-4c70-918b-648255db750f", "luxury-camp-v2.avif"),
  deluxeSwiss: A("a9737693-e198-4c3c-ba6f-7b5b92487c01", "deluxe-swiss-v2.jpg"),
  standardCamp: A("1432e775-febc-455f-aa3a-25a33b504361", "standard-camp.jpg"),
  mudHut: A("f329854c-3dc9-48b4-8992-cd0b5fda634b", "mud-hut.jpg"),
  fort: A("d1bf2cab-c692-4c1b-9504-76c46d2707d8", "fort.jpg"),
  patwon: A("418dea09-f70a-4f88-beb2-7be2cef4d970", "patwon.jpg"),
  gadisar: A("ef9ef3d5-8c59-47aa-9410-24125376c61d", "gadisar.jpg"),
  kuldhara: A("971ad07e-a1c5-459f-a63d-f3203701e1ef", "kuldhara.webp"),
  longewala: A("d50130cf-bcce-4e60-974d-cdadaa8ad944", "longewala.jpg"),
  tanot: A("f94cb52e-a6de-4ea7-8c41-8729ef7ac08e", "tanot.jpg"),
  badabagh: A("207bc4f3-848d-4662-8c30-e6d978ccc6e6", "badabagh.jpg"),
  dune4x4: A("d0890eca-4e6e-4fb5-8e25-d3e8090b807a", "dune-4x4-v2.jpg"),
  quad: A("cc5ff9f1-54f4-4fb5-bb3d-b899aa895a5a", "quad.jpg"),
  sandboarding: A("ff57a743-3027-4f40-8c1b-af0ecc2c3654", "sandboarding.jpg"),
  picnic: A("18735e1d-b91a-426c-bfd7-0e5eb3232681", "picnic.jpg"),
  stargazing: A("d2ae74a8-dd0a-4223-a902-3aae8a4430ba", "stargazing.jpg"),
  royalCandle: A("eb8335c5-db22-4e1d-a339-c35a4f984910", "royal-candle.jpg"),
  photography: A("9bd43ff1-be7b-4e4b-aff4-fa9754c21066", "photography.jpg"),
  wedding: A("2a154e8a-f904-4a92-8a83-57a75390af1c", "wedding.webp"),
  candleDinner: A("727a9f56-7ac4-4114-952d-e8ac7502019a", "candle-dinner.jpg"),
  birthday: A("a68009a4-786e-42b7-8360-586e884161c3", "birthday.jpg"),
  selfDrive: A("bbbcba69-6d05-4d06-b7cf-3cec37d84927", "self-drive-dzire.jpg"),
  luxuryBus: A("4ecedfc3-eb17-4783-9dca-a6fca87acdab", "luxury-bus.jpg"),
  suv: A("8871026f-5866-4577-a0b9-9e30d0f7121f", "suv.avif"),
  tempo: A("82bc256f-32bf-4a59-8eb2-31bde14bec24", "tempo.avif"),
  sedan: A("c5747f02-abb4-40fd-9ab1-802975f410f0", "sedan.avif"),
  homeHero: A("72997d79-fb8f-4c0a-9106-616c67494be1", "home-hero.jpg"),
};

export const HOME_HERO = IMG.homeHero;

const flickr = (tags: string, lock: number) =>
  `https://loremflickr.com/1600/1000/${tags}?lock=${lock}`;

export type Tour = {
  title: string;
  price?: string;
  image: string;
  paragraphs: string[];
  note?: string;
};

export const CAMEL_TOURS: Tour[] = [
  { title: "Half-Day Sunrise Camel Safari", price: "starts at ₹2,150 per person", image: IMG.sunriseSafari,
    paragraphs: [
      "Perfect for early risers who want to catch the desert waking up.",
      "Pickup from your Jaisalmer hotel before dawn, jeep ride to the starting point.",
      "1.5 to 2 hours on camelback into the quieter dunes.",
      "Hot breakfast cooked over an open fire on the sand — chai, eggs, toast, seasonal fruit.",
      "Plenty of time to photograph the horizon turning gold.",
      "Back in the city by late morning with the whole day still free to explore.",
    ],
    note: "Starts around 5:00 am and ends around 11:00 am the same day." },
  { title: "Half-Day Sunset Camel Safari", price: "starts at ₹2,250 per person", image: flickr("camel,sunset,thar", 102),
    paragraphs: [
      "A relaxed evening escape into the Thar for travellers who spend their day sightseeing.",
      "Jeep transfer from Jaisalmer city to the safari start point.",
      "Sunset camel ride across the ridges with your local guide.",
      "Bonfire, snacks and masala chai as the sky changes colour.",
      "Freshly-cooked Rajasthani dinner in the dunes — dal, sabzi, roti and rice.",
      "Return jeep drop to your hotel the same night.",
    ],
    note: "Starts around 1:30 pm and ends around 9:30 pm the same day." },
  { title: "One Day Camel Safari", price: "starts at ₹2,550 per person (min. 2)", image: IMG.oneDay,
    paragraphs: [
      "A full day in the Thar without spending the night.",
      "Breakfast, lunch and dinner all included and cooked in the desert.",
      "Cool morning camel ride followed by rest under a tree at midday.",
      "Second camel ride out to the dunes for sunset.",
      "Complete jeep support with drinking water throughout the day.",
      "Small group and family friendly — no camping equipment needed.",
    ],
    note: "Starts around 6:30 am and ends around 9:30 pm the same day." },
  { title: "Overnight Camel Safari – Route A", price: "starts at ₹3,450 per person", image: IMG.routeA,
    paragraphs: [
      "A non-touristic overnight ride off the standard Sam Dunes trail.",
      "Landscape of small huts, temples, farms and local desert wildlife.",
      "Traditional lunch and dinner cooked over an open fire.",
      "Sleep in the open on warm, cosy bedding rolled out on the sand.",
      "Sunrise on the dunes followed by breakfast and the ride back.",
      "No crowds, no loudspeakers — just the desert.",
    ],
    note: "Starts around 6:30 am and ends around 11:00 am the next day." },
  { title: "Overnight Camel Safari – Route B", price: "starts at ₹3,950 per person", image: flickr("thar,rajasthan,camel", 105),
    paragraphs: [
      "For travellers who want the full nomadic feel across multiple terrains.",
      "Trail stitches together arid scrubland, farms, rocky outcrops and dunes.",
      "Two long camel rides — one in the evening, one in the morning.",
      "All three meals cooked traditionally in the desert.",
      "Night sleeping under an open sky in warm bedding.",
      "Wake up with the desert instead of an alarm clock.",
    ],
    note: "Starts around 6:30 am and ends around 5:30 pm the next day." },
  { title: "Camping in the Desert", price: "starts at ₹3,250 per person", image: IMG.camping,
    paragraphs: [
      "Built for travellers who want the tent experience.",
      "Private canvas camping tent set up on the sand with lanterns.",
      "Camel ride through varied terrain to reach the camp.",
      "Bonfire, dinner and folk music under the stars.",
      "Bedding, pillows and towels included.",
      "Morning tea followed by the return ride.",
    ],
    note: "Starts around 1:30 pm and ends around 11:00 am the next day." },
  { title: "Real Desert Safari (2 Nights)", price: "starts at ₹7,750 per person", image: IMG.realDesert,
    paragraphs: [
      "A two-night journey mixing ruggedness and luxury.",
      "Night 1 — sleep under the stars in the open desert.",
      "Night 2 — luxury desert camp with attached bathroom and hot water.",
      "Multiple camel rides across changing landscapes.",
      "Cultural evening with folk dance and live music.",
      "Both a sunset and a sunrise on the dunes.",
    ],
    note: "Starts around 1:30 pm and ends around 11:00 am on day three." },
  { title: "Camel Safari with Live Entertainment", price: "starts at ₹3,450 per person", image: IMG.liveEntertainment,
    paragraphs: [
      "Classic sunset camel ride with a proper cultural evening.",
      "Ride out to a quiet dune spot for the sunset.",
      "Local gypsy musicians perform live around the fire.",
      "Traditional Rajasthani dinner served under the sky.",
      "Return jeep transfer to Jaisalmer the same night.",
      "Great option for first-time visitors and small groups.",
    ],
    note: "Starts around 1:30 pm and ends around 9:30 pm the same day." },
  { title: "Camel Safari with Dance & Music", price: "starts at ₹4,250 per person", image: IMG.danceMusic,
    paragraphs: [
      "The full cultural version of the overnight experience.",
      "Sunset camel ride into the dunes.",
      "Live Rajasthani folk dance and music performance.",
      "Multi-course traditional dinner.",
      "Night under the stars on comfortable bedding.",
      "Sunrise breakfast before the ride back.",
    ],
    note: "Starts around 1:30 pm and ends around 11:00 am the next day." },
  { title: "Camel Safari with Cultural Program", price: "starts at ₹3,250 per person", image: IMG.cultural,
    paragraphs: [
      "A more refined version of the cultural evening.",
      "Proper welcome, cushioned seating and decorated setting.",
      "Short camel ride for those who prefer a shorter time on camelback.",
      "Full folk music and dance performance.",
      "Multi-course Rajasthani dinner served at the camp.",
      "Ideal for families and older travellers.",
    ],
    note: "Starts around 3:00 pm and ends around 10:30 pm the same day." },
  { title: "Non-Touristic Desert Safari (2N/3D)", price: "starts at ₹2,250 per person / night", image: IMG.nonTouristic,
    paragraphs: [
      "Three days deep into landscapes most travellers never see.",
      "Arid scrubland, farms, rocky outcrops and remote dune belts.",
      "All meals cooked over an open fire.",
      "Two nights sleeping under an open sky.",
      "Jeep support and drinking water throughout.",
      "Custom start/end times available.",
    ],
    note: "Starts at 6:30 am or 1:30 pm; ends at 11:00 am or 5:30 pm on day three." },
  { title: "Thar Desert Safari (4N/5D)", price: "starts at ₹2,050 per person / night", image: IMG.thar4n5d,
    paragraphs: [
      "A longer journey for travellers who want to fully switch off.",
      "Five days, four nights entirely inside the desert.",
      "Rides across changing terrain each day.",
      "All meals traditional, cooked on the sand.",
      "Nights under an open sky with warm bedding.",
      "Perfect for photographers and slow-travel lovers.",
    ],
    note: "Starts at 6:30 am or 1:30 pm; ends at 11:00 am or 5:30 pm on day five." },
  { title: "Exploring The Thar (6N/7D)", price: "starts at ₹1,850 per person / night", image: flickr("expedition,desert,dunes", 117),
    paragraphs: [
      "A week-long expedition across the widest variety of desert landscapes.",
      "Seven days of camel travel with a full support crew.",
      "Six nights sleeping in the open desert.",
      "Visits to remote villages and small shrines.",
      "All meals, water and bedding included.",
      "One of our most immersive itineraries.",
    ],
    note: "Starts at 6:30 am or 1:30 pm; ends at 11:00 am or 5:30 pm on day seven." },
  { title: "Thar by the Compass (7N/8D)", price: "starts at ₹1,750 per person / night", image: IMG.thar7n8d,
    paragraphs: [
      "The longest of our fixed itineraries — eight days of camel travel.",
      "A real expedition for travellers who want a challenge and a reward.",
      "Route covers the deep interior of the Thar.",
      "All meals cooked traditionally in the desert.",
      "Nights sleeping under an open sky.",
      "Full jeep support and drinking water throughout.",
    ],
    note: "Starts at 6:30 am or 1:30 pm; ends at 11:00 am or 5:30 pm on day eight." },
];


export const DESERT_CAMPS: Tour[] = [
  { title: "Luxury Desert Camp", price: "starts at ₹5,500 per night", image: IMG.luxuryCamp,
    paragraphs: [
      "Our flagship camp in the Sam dunes.",
      "Spacious swiss tents with private verandah.",
      "En-suite bathrooms with running hot water.",
      "King-size beds with premium linen.",
      "Dinner buffet served under the stars.",
      "Cultural evening with folk music and dance.",
      "Jeep transfer from Jaisalmer city included.",
      "Complimentary sunrise camel ride the next morning.",
    ],
    note: "Check-in from 3:00 pm, check-out by 11:00 am." },
  { title: "Deluxe Swiss Tent", price: "starts at ₹4,200 per night", image: IMG.deluxeSwiss,
    paragraphs: [
      "Beautifully decorated interiors with traditional Rajasthani textiles.",
      "Real bed with proper mattress and quilts.",
      "Attached bathroom with running hot water.",
      "Private sit-out in front of the tent.",
      "Multi-course dinner and breakfast included.",
      "Cultural program with folk performers each evening.",
      "Perfect balance of comfort and desert feel.",
    ],
    note: "Includes dinner, breakfast and a cultural program." },
  { title: "Standard Desert Camp", price: "starts at ₹2,800 per night", image: IMG.standardCamp,
    paragraphs: [
      "Simple, clean canvas tents on the sand.",
      "Shared bathrooms with running water.",
      "Bedding, pillows and towels provided.",
      "Traditional dinner and breakfast included.",
      "Bonfire and folk music every night.",
      "Great value for backpackers and student groups.",
    ],
    note: "Includes bedding, dinner, breakfast and bonfire." },
];


export const SIGHTSEEING: Tour[] = [
  { title: "Jaisalmer Fort", price: "half-day tour • from ₹1,200", image: IMG.fort,
    paragraphs: [
      "UNESCO World Heritage site and one of the few living forts in the world.",
      "Still home to families, shops and small guesthouses inside the walls.",
      "Walk the ramparts and see the entire city from above.",
      "Visit the intricate Jain temples inside the fort.",
      "Explore the royal palace complex with our local guide.",
      "Best photographed at sunrise or sunset.",
    ] },
  { title: "Patwon ki Haveli", price: "add-on • from ₹800", image: IMG.patwon,
    paragraphs: [
      "A cluster of five havelis in the heart of the old city.",
      "Famous for intricate sandstone jharokhas and carved facades.",
      "One of the finest examples of desert merchant architecture.",
      "Small museum inside with period artefacts.",
      "Roof terrace offers great views of the fort.",
      "Easy to combine with a walk through the old market.",
    ] },
  { title: "Gadisar Lake", price: "sunrise / sunset visit • from ₹700", image: IMG.gadisar,
    paragraphs: [
      "A calm man-made lake surrounded by ghats and small temples.",
      "Best visited at sunrise or sunset for the light.",
      "Boat rides available on the water.",
      "Migratory birds visible in winter months.",
      "Beautiful ornamental gateway at the entrance.",
      "Peaceful place to sit and unwind after a busy day.",
    ] },
  { title: "Kuldhara Abandoned Village", price: "half-day tour • from ₹1,500", image: IMG.kuldhara,
    paragraphs: [
      "Ruins of an entire village abandoned overnight in the 19th century.",
      "Quiet, atmospheric and full of local stories.",
      "Restored temple at the centre of the village.",
      "Wide open views of the surrounding desert.",
      "Combine with a stop at nearby Khaba fort.",
      "Great for photography and slow exploration.",
    ] },
  { title: "Longewala War Memorial", price: "full-day tour • from ₹3,500", image: IMG.longewala,
    paragraphs: [
      "Border war memorial from the 1971 Indo-Pak conflict.",
      "Preserved tanks and armoured vehicles on display.",
      "Small museum with photos, weapons and archives.",
      "Long desert drive from Jaisalmer with beautiful stretches.",
      "Usually combined with Tanot Mata on the same day.",
      "A must for history lovers and families with older kids.",
    ] },
  { title: "Tanot Mata Temple", price: "included with border tour", image: IMG.tanot,
    paragraphs: [
      "A revered temple close to the international border.",
      "Famous for the miracles associated with the 1971 war.",
      "Small BSF museum next to the temple.",
      "Simple langar (community meal) available.",
      "Route passes desert stretches you won't see on standard tours.",
      "Best combined with Longewala as a single day trip.",
    ] },
  { title: "Bada Bagh Cenotaphs", price: "sunset visit • from ₹900", image: IMG.badabagh,
    paragraphs: [
      "Sandstone chhatris built in memory of the Bhati rulers.",
      "Rows of cenotaphs set on a low hill.",
      "Best photographed against the golden hour sky.",
      "Wind farms in the background make for dramatic frames.",
      "Quiet and uncrowded compared to city monuments.",
      "Only a short drive from Jaisalmer city.",
    ] },
];

export const ADVENTURE: Tour[] = [
  { title: "4×4 Dune Bashing", price: "from ₹2,500 per vehicle", image: IMG.dune4x4,
    paragraphs: [
      "A proper adrenaline run across the softer dunes.",
      "Modified 4×4 vehicles built for the sand.",
      "Local drivers who ride these dunes almost every day.",
      "Short safety briefing before every ride.",
      "20–30 minutes of driving across changing dunes.",
      "Great add-on to a sunset camel safari.",
    ] },
  { title: "Quad ATV Rides", price: "from ₹1,800 per ride", image: IMG.quad,
    paragraphs: [
      "Take the controls yourself on a quad bike.",
      "Race across a marked dune circuit.",
      "Short instruction session for first-time riders.",
      "Helmet and goggles included.",
      "Great for teens and adults with no prior experience.",
      "Short ride, big rush.",
    ] },
  { title: "Sandboarding", price: "from ₹800 per person", image: IMG.sandboarding,
    paragraphs: [
      "Snowboarding — minus the snow.",
      "Great fun for kids and adults.",
      "Runs down the softer, gentler slopes.",
      "Boards and basic instruction included.",
      "Photo assistance from our staff.",
      "Perfect quick add-on with any safari.",
    ] },
  { title: "Parasailing", price: "from ₹1,000 per person", image: "https://i.ibb.co/N671jDfS/parasailing-at-jaisalmer.jpg",
    paragraphs: [
      "Get lifted into the desert sky behind a jeep.",
      "Bird's-eye view of the dunes below.",
      "Full safety briefing with certified operators.",
      "Harness, helmet and life-jacket provided.",
      "Perfect for first-time flyers.",
      "One of the highest-rated adventure add-ons in Jaisalmer.",
    ] },
  { title: "Paramotoring", price: "on request", image: "https://i.ibb.co/prK7RzT4/images-1.jpg",
    paragraphs: [
      "Motor-powered paraglider flight over the Thar.",
      "Tandem flight with an experienced pilot.",
      "Aerial views of the dunes, camel trails and camps.",
      "Full flight briefing and safety gear provided.",
      "GoPro footage available on request.",
      "Weather-dependent — best booked a day in advance.",
    ] },

];

export const EXOTIC: Tour[] = [
  { title: "Private Sunset Picnic in the Dunes", price: "Evening Experience • from ₹3,499 per couple", image: IMG.picnic,
    paragraphs: [
      "Escape the crowds and enjoy a beautifully arranged private picnic.",
      "Cushions, low tables and lanterns set up on the golden dunes.",
      "Refreshments, local snacks and chai included.",
      "Breathtaking sunset views over the sand.",
      "Ideal for couples, proposals, anniversaries and photographers.",
      "Full privacy — your own spot in the desert.",
    ] },
  { title: "Stargazing in the Thar Desert", price: "Night Experience • from ₹2,999 per person", image: IMG.stargazing,
    paragraphs: [
      "Experience one of India's clearest night skies.",
      "Far away from city lights and light pollution.",
      "Traditional tea and snacks around a bonfire.",
      "Warm blankets and cushioned seating.",
      "Milky Way visible on clear nights.",
      "Best booked around new moon dates for the darkest sky.",
    ] },
  { title: "Royal Candlelight Dinner in the Desert", price: "Private Dining • from ₹4,999 per couple", image: IMG.royalCandle,
    paragraphs: [
      "A beautifully decorated private setup in the dunes.",
      "Candlelight, flowers and traditional lanterns.",
      "Authentic multi-course Rajasthani dinner.",
      "Live folk music playing softly in the background.",
      "Complete privacy with your own attendant.",
      "One of the most romantic experiences in Jaisalmer.",
    ] },
  { title: "Desert Photography Tour", price: "Half Day • from ₹4,499 per person", image: IMG.photography,
    paragraphs: [
      "Curated tour with a local guide who knows the best photo spots.",
      "Hidden dunes and abandoned villages away from tourists.",
      "Secret sunset locations with clean foregrounds.",
      "Golden-hour light on sandstone architecture.",
      "Perfect for photographers, influencers and content creators.",
      "Private vehicle throughout the shoot.",
    ] },
  { title: "Desert National Park Trip", price: "Full Day • from ₹3,999 per person", image: "https://i.ibb.co/LzR53Y9D/images-2.jpg",
    paragraphs: [
      "Explore one of India's largest and most unique national parks.",
      "Home to the endangered Great Indian Bustard.",
      "Vast open landscapes of dunes, salt flats and thorn scrub.",
      "Chances to spot desert fox, chinkara and Indian gazelle.",
      "Local naturalist guide with jeep safari through the park.",
      "Packed lunch and drinking water included.",
      "Great for wildlife lovers and photographers.",
    ] },
  { title: "Akal Wood Fossil Park", price: "Half Day • from ₹2,499 per person", image: "https://i.ibb.co/xqdkdtCm/unnamed.webp",
    paragraphs: [
      "Walk among 180-million-year-old fossilised tree trunks.",
      "One of the most important geological sites in India.",
      "Sheltered display area preserving the largest fossils.",
      "Guided walk explaining the Jurassic-era history of the region.",
      "Photogenic setting with sandstone rocks and open sky.",
      "Perfect add-on for a Longewala or Tanot day trip.",
    ] },

];

export const EVENTS: Tour[] = [
  { title: "Desert Wedding", price: "custom packages on request", image: IMG.wedding,
    paragraphs: [
      "Full-service wedding planning in the dunes.",
      "Mandap, marigold decor and traditional setup.",
      "Multi-cuisine catering with live counters.",
      "Folk performers, dhol players and fire dancers.",
      "Photography and videography teams available.",
      "Guest transfers, accommodation and logistics handled end-to-end.",
    ] },
  { title: "Private Candlelight Dinner", price: "from ₹6,500 per couple", image: IMG.candleDinner,
    paragraphs: [
      "Private table set up on the dunes just for you.",
      "Lanterns, candles and a floral centrepiece.",
      "Multi-course menu with your choice of veg or non-veg.",
      "Personal attendant throughout the evening.",
      "Optional live music or musician on request.",
      "Ideal for anniversaries, honeymoons and proposals.",
    ] },
  { title: "Birthdays & Small Celebrations", price: "from ₹4,500", image: IMG.birthday,
    paragraphs: [
      "Decorated tents with lights and balloons.",
      "Cake, snacks and dinner arranged on request.",
      "Private folk performance for the group.",
      "Bonfire and games for kids.",
      "Photography package available.",
      "Great for family gatherings and kids' groups.",
    ] },
];

export const TAXIS: Tour[] = [
  { title: "Self-Driving Cars", image: IMG.selfDrive,
    paragraphs: [
      "Rent a well-maintained car and drive Jaisalmer at your own pace.",
      "Hatchbacks, sedans and SUVs available.",
      "Daily and multi-day rental options.",
      "Simple paperwork with minimal deposit.",
      "Unlimited-kilometer packages on request.",
      "24×7 roadside support anywhere in Rajasthan.",
    ],
    note: "Message us for available models and drop locations." },
  { title: "Luxury Bus (35 Seater)", image: IMG.luxuryBus,
    paragraphs: [
      "AC luxury coach for large groups, weddings and corporate offsites.",
      "Pushback seats with generous legroom.",
      "Large luggage bay for group travel.",
      "Experienced driver used to long Rajasthan routes.",
      "Ideal for Jaisalmer sightseeing and intercity tours.",
      "Also available for airport group transfers.",
    ] },
  { title: "Sedan (Dzire / Etios)", image: IMG.sedan,
    paragraphs: [
      "Comfortable AC sedan for up to 3 passengers with luggage.",
      "Perfect for airport transfers and couples.",
      "Great for short sightseeing trips around Jaisalmer.",
      "Clean, well-maintained interiors on every ride.",
      "Local driver with knowledge of the city.",
      "Complimentary bottled water.",
    ] },
  { title: "XUV / SUV (Scorpio / XUV 700)", image: IMG.suv,
    paragraphs: [
      "Spacious SUV for families and small groups.",
      "The right choice for border-area runs like Tanot and Longewala.",
      "Extra ground clearance for rural roads.",
      "AC, music and comfortable seating.",
      "Experienced driver used to rural Rajasthan routes.",
      "Available daily or for full multi-day trips.",
    ] },
  { title: "Tempo Traveller (17 Seater)", image: IMG.tempo,
    paragraphs: [
      "AC minibus for larger families and groups.",
      "Pushback seats with reading lights.",
      "Plenty of luggage space at the back.",
      "Great for Rajasthan circuits and group sightseeing.",
      "Available on daily rental or full-trip basis.",
      "Experienced driver included.",
    ] },
];
