/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourPackagesRouteImport } from './routes/tour-packages'
import { Route as TaxiRouteImport } from './routes/taxi'
import { Route as SpecialEventsRouteImport } from './routes/special-events'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SightseeingRouteImport } from './routes/sightseeing'
import { Route as HotelRouteImport } from './routes/hotel'
import { Route as ExoticToursRouteImport } from './routes/exotic-tours'
import { Route as DesertCampRouteImport } from './routes/desert-camp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CamelSafariRouteImport } from './routes/camel-safari'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSamSandDunesGuideRouteImport } from './routes/blog/sam-sand-dunes-guide'
import { Route as BlogLodurvaExcursionGuideRouteImport } from './routes/blog/lodurva-excursion-guide'
import { Route as BlogJaisalmerWarMuseumRouteImport } from './routes/blog/jaisalmer-war-museum'
import { Route as BlogJaisalmerShoppingGuideRouteImport } from './routes/blog/jaisalmer-shopping-guide'
import { Route as BlogJaisalmerNightlifeGuideRouteImport } from './routes/blog/jaisalmer-nightlife-guide'
import { Route as BlogJaisalmerLocalFoodGuideRouteImport } from './routes/blog/jaisalmer-local-food-guide'
import { Route as BlogJaisalmerHoneymoonCouplesGuideRouteImport } from './routes/blog/jaisalmer-honeymoon-couples-guide'
import { Route as BlogCandlelightDinnerDesertDiningRouteImport } from './routes/blog/candlelight-dinner-desert-dining'
import { Route as ApiPublicBookingVerifyRouteImport } from './routes/api/public/booking-verify'
import { Route as ApiPublicBookingOrderRouteImport } from './routes/api/public/booking-order'

const TourPackagesRoute = TourPackagesRouteImport.update({
  id: '/tour-packages',
  path: '/tour-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxiRoute = TaxiRouteImport.update({
  id: '/taxi',
  path: '/taxi',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialEventsRoute = SpecialEventsRouteImport.update({
  id: '/special-events',
  path: '/special-events',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SightseeingRoute = SightseeingRouteImport.update({
  id: '/sightseeing',
  path: '/sightseeing',
  getParentRoute: () => rootRouteImport,
} as any)
const HotelRoute = HotelRouteImport.update({
  id: '/hotel',
  path: '/hotel',
  getParentRoute: () => rootRouteImport,
} as any)
const ExoticToursRoute = ExoticToursRouteImport.update({
  id: '/exotic-tours',
  path: '/exotic-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const DesertCampRoute = DesertCampRouteImport.update({
  id: '/desert-camp',
  path: '/desert-camp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CamelSafariRoute = CamelSafariRouteImport.update({
  id: '/camel-safari',
  path: '/camel-safari',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSamSandDunesGuideRoute = BlogSamSandDunesGuideRouteImport.update({
  id: '/blog/sam-sand-dunes-guide',
  path: '/blog/sam-sand-dunes-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLodurvaExcursionGuideRoute =
  BlogLodurvaExcursionGuideRouteImport.update({
    id: '/blog/lodurva-excursion-guide',
    path: '/blog/lodurva-excursion-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogJaisalmerWarMuseumRoute = BlogJaisalmerWarMuseumRouteImport.update({
  id: '/blog/jaisalmer-war-museum',
  path: '/blog/jaisalmer-war-museum',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogJaisalmerShoppingGuideRoute =
  BlogJaisalmerShoppingGuideRouteImport.update({
    id: '/blog/jaisalmer-shopping-guide',
    path: '/blog/jaisalmer-shopping-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogJaisalmerNightlifeGuideRoute =
  BlogJaisalmerNightlifeGuideRouteImport.update({
    id: '/blog/jaisalmer-nightlife-guide',
    path: '/blog/jaisalmer-nightlife-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogJaisalmerLocalFoodGuideRoute =
  BlogJaisalmerLocalFoodGuideRouteImport.update({
    id: '/blog/jaisalmer-local-food-guide',
    path: '/blog/jaisalmer-local-food-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogJaisalmerHoneymoonCouplesGuideRoute =
  BlogJaisalmerHoneymoonCouplesGuideRouteImport.update({
    id: '/blog/jaisalmer-honeymoon-couples-guide',
    path: '/blog/jaisalmer-honeymoon-couples-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogCandlelightDinnerDesertDiningRoute =
  BlogCandlelightDinnerDesertDiningRouteImport.update({
    id: '/blog/candlelight-dinner-desert-dining',
    path: '/blog/candlelight-dinner-desert-dining',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBookingVerifyRoute = ApiPublicBookingVerifyRouteImport.update({
  id: '/api/public/booking-verify',
  path: '/api/public/booking-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingOrderRoute = ApiPublicBookingOrderRouteImport.update({
  id: '/api/public/booking-order',
  path: '/api/public/booking-order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/camel-safari': typeof CamelSafariRoute
  '/contact': typeof ContactRoute
  '/desert-camp': typeof DesertCampRoute
  '/exotic-tours': typeof ExoticToursRoute
  '/hotel': typeof HotelRoute
  '/sightseeing': typeof SightseeingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/special-events': typeof SpecialEventsRoute
  '/taxi': typeof TaxiRoute
  '/tour-packages': typeof TourPackagesRoute
  '/blog/candlelight-dinner-desert-dining': typeof BlogCandlelightDinnerDesertDiningRoute
  '/blog/jaisalmer-honeymoon-couples-guide': typeof BlogJaisalmerHoneymoonCouplesGuideRoute
  '/blog/jaisalmer-local-food-guide': typeof BlogJaisalmerLocalFoodGuideRoute
  '/blog/jaisalmer-nightlife-guide': typeof BlogJaisalmerNightlifeGuideRoute
  '/blog/jaisalmer-shopping-guide': typeof BlogJaisalmerShoppingGuideRoute
  '/blog/jaisalmer-war-museum': typeof BlogJaisalmerWarMuseumRoute
  '/blog/lodurva-excursion-guide': typeof BlogLodurvaExcursionGuideRoute
  '/blog/sam-sand-dunes-guide': typeof BlogSamSandDunesGuideRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/booking-order': typeof ApiPublicBookingOrderRoute
  '/api/public/booking-verify': typeof ApiPublicBookingVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/camel-safari': typeof CamelSafariRoute
  '/contact': typeof ContactRoute
  '/desert-camp': typeof DesertCampRoute
  '/exotic-tours': typeof ExoticToursRoute
  '/hotel': typeof HotelRoute
  '/sightseeing': typeof SightseeingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/special-events': typeof SpecialEventsRoute
  '/taxi': typeof TaxiRoute
  '/tour-packages': typeof TourPackagesRoute
  '/blog/candlelight-dinner-desert-dining': typeof BlogCandlelightDinnerDesertDiningRoute
  '/blog/jaisalmer-honeymoon-couples-guide': typeof BlogJaisalmerHoneymoonCouplesGuideRoute
  '/blog/jaisalmer-local-food-guide': typeof BlogJaisalmerLocalFoodGuideRoute
  '/blog/jaisalmer-nightlife-guide': typeof BlogJaisalmerNightlifeGuideRoute
  '/blog/jaisalmer-shopping-guide': typeof BlogJaisalmerShoppingGuideRoute
  '/blog/jaisalmer-war-museum': typeof BlogJaisalmerWarMuseumRoute
  '/blog/lodurva-excursion-guide': typeof BlogLodurvaExcursionGuideRoute
  '/blog/sam-sand-dunes-guide': typeof BlogSamSandDunesGuideRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/booking-order': typeof ApiPublicBookingOrderRoute
  '/api/public/booking-verify': typeof ApiPublicBookingVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/camel-safari': typeof CamelSafariRoute
  '/contact': typeof ContactRoute
  '/desert-camp': typeof DesertCampRoute
  '/exotic-tours': typeof ExoticToursRoute
  '/hotel': typeof HotelRoute
  '/sightseeing': typeof SightseeingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/special-events': typeof SpecialEventsRoute
  '/taxi': typeof TaxiRoute
  '/tour-packages': typeof TourPackagesRoute
  '/blog/candlelight-dinner-desert-dining': typeof BlogCandlelightDinnerDesertDiningRoute
  '/blog/jaisalmer-honeymoon-couples-guide': typeof BlogJaisalmerHoneymoonCouplesGuideRoute
  '/blog/jaisalmer-local-food-guide': typeof BlogJaisalmerLocalFoodGuideRoute
  '/blog/jaisalmer-nightlife-guide': typeof BlogJaisalmerNightlifeGuideRoute
  '/blog/jaisalmer-shopping-guide': typeof BlogJaisalmerShoppingGuideRoute
  '/blog/jaisalmer-war-museum': typeof BlogJaisalmerWarMuseumRoute
  '/blog/lodurva-excursion-guide': typeof BlogLodurvaExcursionGuideRoute
  '/blog/sam-sand-dunes-guide': typeof BlogSamSandDunesGuideRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/booking-order': typeof ApiPublicBookingOrderRoute
  '/api/public/booking-verify': typeof ApiPublicBookingVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adventure'
    | '/camel-safari'
    | '/contact'
    | '/desert-camp'
    | '/exotic-tours'
    | '/hotel'
    | '/sightseeing'
    | '/sitemap.xml'
    | '/special-events'
    | '/taxi'
    | '/tour-packages'
    | '/blog/candlelight-dinner-desert-dining'
    | '/blog/jaisalmer-honeymoon-couples-guide'
    | '/blog/jaisalmer-local-food-guide'
    | '/blog/jaisalmer-nightlife-guide'
    | '/blog/jaisalmer-shopping-guide'
    | '/blog/jaisalmer-war-museum'
    | '/blog/lodurva-excursion-guide'
    | '/blog/sam-sand-dunes-guide'
    | '/blog/'
    | '/api/public/booking-order'
    | '/api/public/booking-verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adventure'
    | '/camel-safari'
    | '/contact'
    | '/desert-camp'
    | '/exotic-tours'
    | '/hotel'
    | '/sightseeing'
    | '/sitemap.xml'
    | '/special-events'
    | '/taxi'
    | '/tour-packages'
    | '/blog/candlelight-dinner-desert-dining'
    | '/blog/jaisalmer-honeymoon-couples-guide'
    | '/blog/jaisalmer-local-food-guide'
    | '/blog/jaisalmer-nightlife-guide'
    | '/blog/jaisalmer-shopping-guide'
    | '/blog/jaisalmer-war-museum'
    | '/blog/lodurva-excursion-guide'
    | '/blog/sam-sand-dunes-guide'
    | '/blog'
    | '/api/public/booking-order'
    | '/api/public/booking-verify'
  id:
    | '__root__'
    | '/'
    | '/adventure'
    | '/camel-safari'
    | '/contact'
    | '/desert-camp'
    | '/exotic-tours'
    | '/hotel'
    | '/sightseeing'
    | '/sitemap.xml'
    | '/special-events'
    | '/taxi'
    | '/tour-packages'
    | '/blog/candlelight-dinner-desert-dining'
    | '/blog/jaisalmer-honeymoon-couples-guide'
    | '/blog/jaisalmer-local-food-guide'
    | '/blog/jaisalmer-nightlife-guide'
    | '/blog/jaisalmer-shopping-guide'
    | '/blog/jaisalmer-war-museum'
    | '/blog/lodurva-excursion-guide'
    | '/blog/sam-sand-dunes-guide'
    | '/blog/'
    | '/api/public/booking-order'
    | '/api/public/booking-verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventureRoute: typeof AdventureRoute
  CamelSafariRoute: typeof CamelSafariRoute
  ContactRoute: typeof ContactRoute
  DesertCampRoute: typeof DesertCampRoute
  ExoticToursRoute: typeof ExoticToursRoute
  HotelRoute: typeof HotelRoute
  SightseeingRoute: typeof SightseeingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpecialEventsRoute: typeof SpecialEventsRoute
  TaxiRoute: typeof TaxiRoute
  TourPackagesRoute: typeof TourPackagesRoute
  BlogCandlelightDinnerDesertDiningRoute: typeof BlogCandlelightDinnerDesertDiningRoute
  BlogJaisalmerHoneymoonCouplesGuideRoute: typeof BlogJaisalmerHoneymoonCouplesGuideRoute
  BlogJaisalmerLocalFoodGuideRoute: typeof BlogJaisalmerLocalFoodGuideRoute
  BlogJaisalmerNightlifeGuideRoute: typeof BlogJaisalmerNightlifeGuideRoute
  BlogJaisalmerShoppingGuideRoute: typeof BlogJaisalmerShoppingGuideRoute
  BlogJaisalmerWarMuseumRoute: typeof BlogJaisalmerWarMuseumRoute
  BlogLodurvaExcursionGuideRoute: typeof BlogLodurvaExcursionGuideRoute
  BlogSamSandDunesGuideRoute: typeof BlogSamSandDunesGuideRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicBookingOrderRoute: typeof ApiPublicBookingOrderRoute
  ApiPublicBookingVerifyRoute: typeof ApiPublicBookingVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tour-packages': {
      id: '/tour-packages'
      path: '/tour-packages'
      fullPath: '/tour-packages'
      preLoaderRoute: typeof TourPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxi': {
      id: '/taxi'
      path: '/taxi'
      fullPath: '/taxi'
      preLoaderRoute: typeof TaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/special-events': {
      id: '/special-events'
      path: '/special-events'
      fullPath: '/special-events'
      preLoaderRoute: typeof SpecialEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sightseeing': {
      id: '/sightseeing'
      path: '/sightseeing'
      fullPath: '/sightseeing'
      preLoaderRoute: typeof SightseeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hotel': {
      id: '/hotel'
      path: '/hotel'
      fullPath: '/hotel'
      preLoaderRoute: typeof HotelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exotic-tours': {
      id: '/exotic-tours'
      path: '/exotic-tours'
      fullPath: '/exotic-tours'
      preLoaderRoute: typeof ExoticToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desert-camp': {
      id: '/desert-camp'
      path: '/desert-camp'
      fullPath: '/desert-camp'
      preLoaderRoute: typeof DesertCampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camel-safari': {
      id: '/camel-safari'
      path: '/camel-safari'
      fullPath: '/camel-safari'
      preLoaderRoute: typeof CamelSafariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/sam-sand-dunes-guide': {
      id: '/blog/sam-sand-dunes-guide'
      path: '/blog/sam-sand-dunes-guide'
      fullPath: '/blog/sam-sand-dunes-guide'
      preLoaderRoute: typeof BlogSamSandDunesGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/lodurva-excursion-guide': {
      id: '/blog/lodurva-excursion-guide'
      path: '/blog/lodurva-excursion-guide'
      fullPath: '/blog/lodurva-excursion-guide'
      preLoaderRoute: typeof BlogLodurvaExcursionGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/jaisalmer-war-museum': {
      id: '/blog/jaisalmer-war-museum'
      path: '/blog/jaisalmer-war-museum'
      fullPath: '/blog/jaisalmer-war-museum'
      preLoaderRoute: typeof BlogJaisalmerWarMuseumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/jaisalmer-shopping-guide': {
      id: '/blog/jaisalmer-shopping-guide'
      path: '/blog/jaisalmer-shopping-guide'
      fullPath: '/blog/jaisalmer-shopping-guide'
      preLoaderRoute: typeof BlogJaisalmerShoppingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/jaisalmer-nightlife-guide': {
      id: '/blog/jaisalmer-nightlife-guide'
      path: '/blog/jaisalmer-nightlife-guide'
      fullPath: '/blog/jaisalmer-nightlife-guide'
      preLoaderRoute: typeof BlogJaisalmerNightlifeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/jaisalmer-local-food-guide': {
      id: '/blog/jaisalmer-local-food-guide'
      path: '/blog/jaisalmer-local-food-guide'
      fullPath: '/blog/jaisalmer-local-food-guide'
      preLoaderRoute: typeof BlogJaisalmerLocalFoodGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/jaisalmer-honeymoon-couples-guide': {
      id: '/blog/jaisalmer-honeymoon-couples-guide'
      path: '/blog/jaisalmer-honeymoon-couples-guide'
      fullPath: '/blog/jaisalmer-honeymoon-couples-guide'
      preLoaderRoute: typeof BlogJaisalmerHoneymoonCouplesGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/candlelight-dinner-desert-dining': {
      id: '/blog/candlelight-dinner-desert-dining'
      path: '/blog/candlelight-dinner-desert-dining'
      fullPath: '/blog/candlelight-dinner-desert-dining'
      preLoaderRoute: typeof BlogCandlelightDinnerDesertDiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-verify': {
      id: '/api/public/booking-verify'
      path: '/api/public/booking-verify'
      fullPath: '/api/public/booking-verify'
      preLoaderRoute: typeof ApiPublicBookingVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-order': {
      id: '/api/public/booking-order'
      path: '/api/public/booking-order'
      fullPath: '/api/public/booking-order'
      preLoaderRoute: typeof ApiPublicBookingOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventureRoute: AdventureRoute,
  CamelSafariRoute: CamelSafariRoute,
  ContactRoute: ContactRoute,
  DesertCampRoute: DesertCampRoute,
  ExoticToursRoute: ExoticToursRoute,
  HotelRoute: HotelRoute,
  SightseeingRoute: SightseeingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpecialEventsRoute: SpecialEventsRoute,
  TaxiRoute: TaxiRoute,
  TourPackagesRoute: TourPackagesRoute,
  BlogCandlelightDinnerDesertDiningRoute:
    BlogCandlelightDinnerDesertDiningRoute,
  BlogJaisalmerHoneymoonCouplesGuideRoute:
    BlogJaisalmerHoneymoonCouplesGuideRoute,
  BlogJaisalmerLocalFoodGuideRoute: BlogJaisalmerLocalFoodGuideRoute,
  BlogJaisalmerNightlifeGuideRoute: BlogJaisalmerNightlifeGuideRoute,
  BlogJaisalmerShoppingGuideRoute: BlogJaisalmerShoppingGuideRoute,
  BlogJaisalmerWarMuseumRoute: BlogJaisalmerWarMuseumRoute,
  BlogLodurvaExcursionGuideRoute: BlogLodurvaExcursionGuideRoute,
  BlogSamSandDunesGuideRoute: BlogSamSandDunesGuideRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicBookingOrderRoute: ApiPublicBookingOrderRoute,
  ApiPublicBookingVerifyRoute: ApiPublicBookingVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
